version: '3.8'
services:
  db:
    container_name: mysql
    #image: smgemelos/raceday-mysql:1.0
    build:
      context: ./
      dockerfile: mysql_dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lcsportident_events
      MYSQL_USER: sportident
      MYSQL_PASSWORD: sportident
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-backup:/db-backup

    ports:
      - "3306:3306"

  raceday-webapp:
    container_name: raceday-webapp
    #image: smgemelos/raceday-web:1.0
    build:
      context: ./
      dockerfile: raceday_dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/

    ports:
      - 80:80


  racetiming:
    container_name: racetiming
    #image: smgemelos/raceday-racetiming:1.0
    build:
      context: ./
      dockerfile: racetiming_dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./log:/var/log
      - ./racetiming:/var/app/racetiming

      

  ceslive:
    container_name: ceslive
    image: smgemelos/raceday-live:1.2
    build:
      context: ./
      dockerfile: ceslive_dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./log:/var/log
      - ./ceslive:/var/app/ceslive


